# Generated by Django 3.0.8 on 2020-08-04 12:10

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('busid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('busname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StartTime',
            fields=[
                ('startid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('startdate', models.DateField()),
                ('starttime', models.TimeField()),
                ('busid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Bus')),
            ],
            options={
                'ordering': ['-startid'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seatid', models.IntegerField(primary_key=True, serialize=False)),
                ('seatrow', models.IntegerField()),
                ('seatcol', models.CharField(max_length=11)),
                ('status', models.BooleanField(default=False)),
                ('startid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.StartTime')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('busid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Bus')),
                ('seatid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Seat')),
                ('startid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.StartTime')),
                ('username', models.ForeignKey(default=accounts.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
